#!/bin/sh

set -e

make OUTNAME=dfu-gtn650g4 HSE_SPEED_MHZ=16 \
    CONFIG="-DENABLE_GPIO_DFU_BOOT -DGPIO_DFU_BOOT_PORT=GPIOA -DGPIO_DFU_BOOT_PIN=2 -DGPIO_DFU_BOOT_PULLUP -DUSB_PULLUP_PORT=GPIOC -DUSB_PULLUP_PIN=10 -DENABLE_SAFEWRITE -DDFU_USB_VID=0x32b6 -DDFU_USB_PID=0x0800 -DDFU_USB_MFG_STRING=\"\\\"RealSimGear Inc\\\"\"" \
    clean all


