#!/bin/sh

set -e

make OUTNAME=dfu-gtn650g4 HSE_SPEED_MHZ=16 LINK_SCRIPT=stm32f103xd.ld \
    USB_VID=0x32b6 USB_PID=0x0800 \
    CONFIG="-DENABLE_GPIO_DFU_BOOT -DGPIO_DFU_BOOT_PORT=GPIOA -DGPIO_DFU_BOOT_PIN=2 -DUSB_PULLUP_PORT=GPIOC -DUSB_PULLUP_PIN=10 -DDFU_USB_MFG_STRING=\"\\\"RealSimGear Inc\\\"\"" \
    clean all

make OUTNAME=dfu-yoke16 HSE_SPEED_MHZ=16 LINK_SCRIPT=stm32f103xd.ld \
    USB_VID=0x32b6 USB_PID=0x0800 \
    CONFIG="-DENABLE_GPIO_DFU_BOOT -DGPIO_DFU_BOOT_PORT=GPIOC -DGPIO_DFU_BOOT_PIN=3 -DGPIO_DFU_BOOT_PULLUP -DUSB_PULLUP_PORT=GPIOC -DUSB_PULLUP_PIN=9 -DDFU_USB_MFG_STRING=\"\\\"RealSimGear Inc\\\"\"" \
    clean all

make OUTNAME=dfu-g1000v8r1 HSE_SPEED_MHZ=16 LINK_SCRIPT=stm32f103xd.ld \
    USB_VID=0x32b6 USB_PID=0x0800 \
    CONFIG="-DENABLE_GPIO_DFU_BOOT -DGPIO_DFU_BOOT_PORT=GPIOB -DGPIO_DFU_BOOT_PIN=1 -DGPIO_DFU_BOOT_PULLUP -DUSB_PULLUP_PORT=GPIOA -DUSB_PULLUP_PIN=10 -DDFU_USB_MFG_STRING=\"\\\"RealSimGear Inc\\\"\"" \
    clean all

make OUTNAME=dfu-capsv2 HSE_SPEED_MHZ=16 LINK_SCRIPT=stm32f103xd.ld \
    USB_VID=0x32b6 USB_PID=0x0800 \
    CONFIG="-DENABLE_GPIO_DFU_BOOT -DGPIO_DFU_BOOT_PORT=GPIOB -DGPIO_DFU_BOOT_PIN=1 -DGPIO_DFU_BOOT_PULLUP -DUSB_PULLUP_PORT=GPIOC -DUSB_PULLUP_PIN=10 -DDFU_USB_MFG_STRING=\"\\\"RealSimGear Inc\\\"\"" \
    clean all
